services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/static:/app/static
      - ./frontend:/frontend
    command: bash -c "export PGPASSWORD='password'; until pg_isready -h db -p 5432 -U postgres; do echo 'Waiting for postgres...'; sleep 2; done; echo 'PostgreSQL ready'; python run.py"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/tourjett
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tourjett
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: